[project]
name = "parsifal-invoke"
version = "1.0.0"
description = "InvokeAI Node for Parsifal Text Generation"
authors = [{ name = "TheCulprit" }]
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"